// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acntkrknnkhhavvzggxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbnRrcmtubmtoaGF2dnpnZ3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3Njc1MjgsImV4cCI6MjA2NzM0MzUyOH0.eFwKcwjsz-pduX-Nrgmr3qhsn3WN17Kfmb7wZYmfckU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});